# Generated by Django 6.0 on 2026-01-06 23:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosPersonales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=60)),
                ('apellidos', models.CharField(max_length=60)),
                ('descripcionperfil', models.TextField(max_length=500)),
                ('nacionalidad', models.CharField(max_length=20)),
                ('fechanacimiento', models.DateField()),
                ('numerocedula', models.CharField(max_length=10, unique=True)),
                ('sexo', models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer')], max_length=1)),
                ('telefonofijo', models.CharField(blank=True, max_length=15)),
                ('direcciondomiciliaria', models.CharField(max_length=100)),
                ('sitioweb', models.URLField(blank=True)),
                ('archivo_cv_pdf', models.FileField(blank=True, null=True, upload_to='cvs/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExperienciaLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrempresa', models.CharField(max_length=100)),
                ('cargodesempenado', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('logros', models.TextField()),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiencias', to='tasks.datospersonales')),
            ],
        ),
        migrations.CreateModel(
            name='Habilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('nivel', models.PositiveIntegerField(default=50)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habilidades', to='tasks.datospersonales')),
            ],
        ),
    ]
