# Generated by Django 6.0 on 2026-01-28 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_datospersonales_experiencialaboral_habilidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reconocimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título del Certificado')),
                ('institucion', models.CharField(max_length=100, verbose_name='Institución')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='certificados/', verbose_name='Foto del Título')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.datospersonales')),
            ],
        ),
    ]
