# Generated by Django 6.0 on 2026-01-28 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_reconocimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='educacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título Obtenido')),
                ('institucion', models.CharField(max_length=100, verbose_name='Institución Educativa')),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='Fecha Inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha Fin (Dejar vacío si cursas actualmente)')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.datospersonales')),
            ],
        ),
    ]
