# Generated by Django 6.0 on 2026-01-28 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_educacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoGarage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Producto')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio ($)')),
                ('imagen', models.ImageField(upload_to='garage/', verbose_name='Foto del Producto')),
                ('stock', models.IntegerField(default=1, verbose_name='Cantidad Disponible')),
            ],
        ),
    ]
