# Generated by Django 6.0 on 2026-01-28 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_productogarage'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecursoAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Área (ej. Backend)')),
                ('descripcion', models.TextField(verbose_name='Tecnologías (ej. Django, APIs)')),
                ('icono', models.CharField(default='fas fa-book', max_length=50, verbose_name='Icono FontAwesome (ej. fab fa-python)')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.datospersonales')),
            ],
        ),
    ]
