# Generated by Django 6.0 on 2026-01-28 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_recursoacademico'),
    ]

    operations = [
        migrations.AddField(
            model_name='habilidad',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Ej: Uso avanzado para Data Science.', null=True, verbose_name='Contexto Corto'),
        ),
        migrations.AddField(
            model_name='habilidad',
            name='porcentaje',
            field=models.IntegerField(default=50, verbose_name='Nivel (0-100)'),
        ),
    ]
