# Generated by Django 6.0 on 2026-02-02 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_habilidad_descripcion_habilidad_porcentaje'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datospersonales',
            name='archivo_cv_pdf',
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='foto_portada',
            field=models.ImageField(blank=True, help_text='Sube una foto cuadrada para la tarjeta de inicioo.', null=True, upload_to='portadas/', verbose_name='Foto de Portada'),
        ),
        migrations.AlterField(
            model_name='educacion',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='educacion',
            name='fecha_inicio',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
