# Generated by Django 6.0 on 2026-02-02 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_remove_datospersonales_archivo_cv_pdf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productogarage',
            name='perfil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='tasks.datospersonales'),
        ),
    ]
