# Generated by Django 6.0 on 2026-02-02 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_productogarage_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='datospersonales',
            name='mostrar_botones',
            field=models.BooleanField(default=True, verbose_name='Mostrar Botones Superiores (Garage, PDF, etc.)'),
        ),
    ]
