# Generated by Django 6.0 on 2026-02-03 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_datospersonales_mostrar_botones'),
    ]

    operations = [
        migrations.AddField(
            model_name='datospersonales',
            name='direcciontrabajo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Dirección Trabajo'),
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='estadocivil',
            field=models.CharField(default='Soltero/a', max_length=20, verbose_name='Estado Civil'),
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='licenciaconducir',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Licencia de Conducir (Tipo)'),
        ),
    ]
