# Generated by Django 6.0 on 2026-02-03 02:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_datospersonales_direcciontrabajo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datospersonales',
            name='telefonoconvencional',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator('^\\d+$', 'Solo se permiten números (0-9).')], verbose_name='Tel. Convencional'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='direcciondomiciliaria',
            field=models.CharField(max_length=100, verbose_name='Domicilio'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='estadocivil',
            field=models.CharField(choices=[('Soltero/a', 'Soltero/a'), ('Casado/a', 'Casado/a'), ('Divorciado/a', 'Divorciado/a'), ('Viudo/a', 'Viudo/a'), ('Unión Libre', 'Unión Libre')], default='Soltero/a', max_length=20, verbose_name='Estado Civil'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='fechanacimiento',
            field=models.DateField(verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='foto_portada',
            field=models.ImageField(blank=True, help_text='Sube una foto cuadrada para la tarjeta de inicio.', null=True, upload_to='portadas/', verbose_name='Foto de Portada'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='licenciaconducir',
            field=models.CharField(blank=True, choices=[('A', 'Tipo A (Motos)'), ('B', 'Tipo B (Autos)'), ('C', 'Tipo C (Taxis)'), ('D', 'Tipo D (Bus)'), ('E', 'Tipo E (Pesados)'), ('F', 'Tipo F (Especiales)'), ('G', 'Tipo G (Maquinaria)')], max_length=5, null=True, verbose_name='Licencia de Conducir'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='nacionalidad',
            field=models.CharField(default='Ecuatoriana', max_length=20),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='numerocedula',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^\\d+$', 'Solo se permiten números (0-9).')], verbose_name='Cédula'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='sitioweb',
            field=models.URLField(blank=True, verbose_name='Sitio Web'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='telefonofijo',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator('^\\d+$', 'Solo se permiten números (0-9).')], verbose_name='Celular/Fijo'),
        ),
    ]
