# Generated by Django 6.0 on 2026-02-03 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_datospersonales_telefonoconvencional_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experiencialaboral',
            name='fecha_fin',
        ),
        migrations.RemoveField(
            model_name='experiencialaboral',
            name='fecha_inicio',
        ),
        migrations.RemoveField(
            model_name='experiencialaboral',
            name='logros',
        ),
        migrations.AddField(
            model_name='experiencialaboral',
            name='activarparaqueseveaenfront',
            field=models.BooleanField(default=True, verbose_name='Mostrar en la Web'),
        ),
        migrations.AddField(
            model_name='experiencialaboral',
            name='descripcionfunciones',
            field=models.TextField(default='Pendiente de llenar', max_length=500, verbose_name='Descripción de Funciones/Logros'),
        ),
        migrations.AddField(
            model_name='experiencialaboral',
            name='emailempresa',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email Empresa'),
        ),
        migrations.AddField(
            model_name='experiencialaboral',
            name='fechafingestion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Fin'),
        ),
        migrations.AddField(
            model_name='experiencialaboral',
            name='fechainiciogestion',
            field=models.DateField(default='2024-01-01', verbose_name='Fecha Inicio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experiencialaboral',
            name='lugarempresa',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Lugar/Ciudad'),
        ),
        migrations.AddField(
            model_name='experiencialaboral',
            name='nombrecontactoempresarial',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre Contacto'),
        ),
        migrations.AddField(
            model_name='experiencialaboral',
            name='rutacertificado',
            field=models.ImageField(blank=True, null=True, upload_to='certificados_laborales/', verbose_name='Certificado Laboral'),
        ),
        migrations.AddField(
            model_name='experiencialaboral',
            name='sitiowebempresa',
            field=models.URLField(blank=True, max_length=100, null=True, verbose_name='Sitio Web Empresa'),
        ),
        migrations.AddField(
            model_name='experiencialaboral',
            name='telefonocontactoempresarial',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Teléfono Contacto'),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='cargodesempenado',
            field=models.CharField(max_length=100, verbose_name='Cargo Desempeñado'),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='nombrempresa',
            field=models.CharField(max_length=50, verbose_name='Nombre de la Empresa'),
        ),
    ]
