# Generated by Django 6.0 on 2026-02-03 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_remove_experiencialaboral_fecha_fin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datospersonales',
            name='mostrar_educacion',
            field=models.BooleanField(default=True, verbose_name='Mostrar Pestaña Educación'),
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='mostrar_experiencia',
            field=models.BooleanField(default=True, verbose_name='Mostrar Pestaña Experiencia'),
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='mostrar_garage',
            field=models.BooleanField(default=True, verbose_name='Mostrar Botón Garage'),
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='mostrar_habilidades',
            field=models.BooleanField(default=True, verbose_name='Mostrar Pestaña Habilidades'),
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='mostrar_reconocimientos',
            field=models.BooleanField(default=True, verbose_name='Mostrar Pestaña Certificados'),
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='mostrar_recursos',
            field=models.BooleanField(default=True, verbose_name='Mostrar Pestaña Recursos'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='mostrar_botones',
            field=models.BooleanField(default=True, verbose_name='Mostrar Botones Superiores'),
        ),
    ]
