# Generated by Django 6.0 on 2026-02-03 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_datospersonales_mostrar_educacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reconocimiento',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='reconocimiento',
            name='institucion',
        ),
        migrations.RemoveField(
            model_name='reconocimiento',
            name='titulo',
        ),
        migrations.AddField(
            model_name='reconocimiento',
            name='activarparaqueseveaenfront',
            field=models.BooleanField(default=True, verbose_name='Mostrar en la Web'),
        ),
        migrations.AddField(
            model_name='reconocimiento',
            name='descripcionreconocimiento',
            field=models.CharField(default='2024-01-01', max_length=100, verbose_name='Nombre del Reconocimiento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reconocimiento',
            name='entidadpatrocinadora',
            field=models.CharField(default='Pendiente', max_length=100, verbose_name='Entidad/Institución'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reconocimiento',
            name='fechareconocimiento',
            field=models.DateField(default='2024-01-01', verbose_name='Fecha'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reconocimiento',
            name='nombrecontactoauspicia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre Contacto'),
        ),
        migrations.AddField(
            model_name='reconocimiento',
            name='rutacertificado',
            field=models.ImageField(blank=True, null=True, upload_to='certificados/', verbose_name='Imagen del Certificado'),
        ),
        migrations.AddField(
            model_name='reconocimiento',
            name='telefonocontactoauspicia',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Teléfono Contacto'),
        ),
        migrations.AddField(
            model_name='reconocimiento',
            name='tiporeconocimiento',
            field=models.CharField(choices=[('Académico', 'Académico'), ('Público', 'Público'), ('Privado', 'Privado')], default='2024-01-05', max_length=100, verbose_name='Tipo de Reconocimiento'),
            preserve_default=False,
        ),
    ]
