# Generated by Django 6.0 on 2026-02-03 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_remove_reconocimiento_imagen_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datospersonales',
            name='mostrar_habilidades',
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='mostrar_cursos',
            field=models.BooleanField(default=True, verbose_name='Mostrar Pestaña Cursos'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='foto_portada',
            field=models.ImageField(blank=True, null=True, upload_to='portadas/', verbose_name='Foto de Portada'),
        ),
        migrations.CreateModel(
            name='CursoRealizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrecurso', models.CharField(max_length=100, verbose_name='Nombre del Curso')),
                ('fechainicio', models.DateField(verbose_name='Fecha Inicio')),
                ('fechafin', models.DateField(verbose_name='Fecha Fin')),
                ('totalhoras', models.IntegerField(verbose_name='Total Horas')),
                ('descripcioncurso', models.CharField(max_length=100, verbose_name='Descripción del Curso')),
                ('entidadpatrocinadora', models.CharField(max_length=100, verbose_name='Entidad Patrocinadora')),
                ('nombrecontactoauspicia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre Contacto')),
                ('telefonocontactoauspicia', models.CharField(blank=True, max_length=60, null=True, verbose_name='Teléfono Contacto')),
                ('emailempresapatrocinadora', models.CharField(blank=True, max_length=60, null=True, verbose_name='Email Empresa')),
                ('activarparaqueseveaenfront', models.BooleanField(default=True, verbose_name='Mostrar en la Web')),
                ('rutacertificado', models.ImageField(blank=True, null=True, upload_to='certificados_cursos/', verbose_name='Certificado')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='tasks.datospersonales')),
            ],
        ),
        migrations.DeleteModel(
            name='Habilidad',
        ),
    ]
