# Generated by Django 6.0 on 2026-02-03 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_remove_datospersonales_mostrar_habilidades_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datospersonales',
            name='mostrar_recursos',
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='mostrar_productos_academicos',
            field=models.BooleanField(default=True, verbose_name='Mostrar Pestaña Productos Académicos'),
        ),
        migrations.CreateModel(
            name='ProductoAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrerecurso', models.CharField(max_length=100, verbose_name='Nombre del Recurso')),
                ('clasificador', models.CharField(max_length=100, verbose_name='Clasificador')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripción')),
                ('activarparaqueseveaenfront', models.BooleanField(default=True, verbose_name='Mostrar en la Web')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.datospersonales')),
            ],
        ),
        migrations.DeleteModel(
            name='RecursoAcademico',
        ),
    ]
