# Generated by Django 6.0 on 2026-02-03 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_remove_datospersonales_mostrar_recursos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datospersonales',
            name='mostrar_educacion',
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='mostrar_productos_laborales',
            field=models.BooleanField(default=True, verbose_name='Mostrar Pestaña Productos Laborales'),
        ),
        migrations.CreateModel(
            name='ProductoLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreproducto', models.CharField(max_length=100, verbose_name='Nombre del Producto')),
                ('fechaproducto', models.DateField(verbose_name='Fecha')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripción')),
                ('activarparaqueseveaenfront', models.BooleanField(default=True, verbose_name='Mostrar en la Web')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.datospersonales')),
            ],
        ),
        migrations.DeleteModel(
            name='educacion',
        ),
    ]
