# Generated by Django 6.0 on 2026-02-03 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0018_remove_datospersonales_mostrar_educacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datospersonales',
            name='mostrar_garage',
            field=models.BooleanField(default=True, verbose_name='Mostrar Botón Venta Garage'),
        ),
        migrations.CreateModel(
            name='VentaGarage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreproducto', models.CharField(max_length=100, verbose_name='Nombre del Producto')),
                ('estadoproducto', models.CharField(choices=[('Bueno', 'Bueno'), ('Regular', 'Regular')], max_length=40, verbose_name='Estado')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripción')),
                ('valordelbien', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Valor del Bien ($)')),
                ('activarparaqueseveaenfront', models.BooleanField(default=True, verbose_name='Mostrar en la Web')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='garage/', verbose_name='Foto del Producto')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas_garage', to='tasks.datospersonales')),
            ],
        ),
        migrations.DeleteModel(
            name='ProductoGarage',
        ),
    ]
